# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13QXzeuiNowEtb_JxDTujUPKETCWC4W83

#### Develop a conversational AI chatbot leveraging transformer-based language models (e.g., BERT, GPT-2, RoBERTa) trained specifically on customer support conversations within the banking sector, potentially exploring advanced or hybrid transformer architectures (e.g., GPT-3, LLaMA, and fine-tuned open-source models) for enhanced capabilities. The chatbot will provide instant, accurate, and contextually relevant responses to common banking queries, effectively simulating human-agent interactions.
"""

# Import Modules

import pandas as pd
import matplotlib as plt
import seaborn as sns

from google.colab import drive
drive.mount('/content/drive')

conversation_data = pd.read_csv(r'/content/drive/MyDrive/chatbot/banking-conversations-sample.csv')

conversation_data.head()

# Clean Text

import re
import html
import pandas as pd
from nltk.corpus import stopwords

def clean_text(text):
    if not isinstance(text, str):
        return ""  # Return empty string for non-string values

    # Decode HTML entities
    text = html.unescape(text)

    # Remove HTML tags
    text = re.sub(r'<.*?>', ' ', text)

    # Normalize case
    text = text.lower()

    # Remove special characters and punctuation
    text = re.sub(r'[^\w\s]', ' ', text)

    # Remove extra whitespace
    text = re.sub(r'\s+', ' ', text).strip()

    # Remove stopwords
    stop_words = set(stopwords.words('english'))
    text = ' '.join(word for word in text.split() if word not in stop_words)

    return text

import warnings
warnings.filterwarnings("ignore")

import nltk
# Download stopwords
nltk.download('stopwords')

# Apply cleaning function
conversation_data["cleaned_text"] = conversation_data["text"].apply(clean_text)

conversation_data.head()

def tokenize_text(text):
    return tokenizer.encode(text, add_special_tokens=True)

import spacy
import os

# Suppress Hugging Face symlink warning
os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"

# Load spaCy model
nlp = spacy.load("en_core_web_sm")

# Define intents and patterns
intent_patterns = {
    # Existing intents
    "check_balance": ["check balance", "account balance", "balance inquiry", "what's my balance"],
    "set_up_payments": ["automatic payment", "set up payment", "schedule payment", "recurring payment"],
    "verify_identity": ["verify identity", "confirm identity", "identity check", "validate identity", "please verify", "security number"],
    "get_account_number": ["account number", "my account", "what's my account number", "check account id"],
    "transfer_money": ["send money", "transfer funds", "move money", "wire transfer"],
    "close_account": ["close account", "terminate account", "cancel account", "delete account"],

    # New intents based on the word cloud
    "greeting": ["hi", "hello", "good morning", "good evening", "welcome"],
    "farewell": ["bye", "goodbye", "thank you", "thanks", "great day"],
    "check_interest_rate": ["interest rate", "rate information", "loan rate", "savings rate"],
    "update_personal_info": ["update name", "change name", "update details", "modify information"],
    "card_services": ["credit card", "debit card", "lost card", "replace card"],
    "report_issue": ["problem", "issue", "inconvenience", "apologize", "error", "frustration"],
    "confirm_transaction": ["transaction status", "check transaction", "verify payment"],
    "open_account": ["open account", "new account", "start account", "create account"],
    "loan_inquiry": ["loan application", "loan status", "apply loan", "loan inquiry"],
    "check_security": ["social security", "security check", "security question"],
    "service_availability": ["working hours", "service time", "support availability"],
    "account_type": ["checking account", "savings account", "account type"],
    "contact_support": ["contact support", "speak agent", "talk to human"],
}

def identify_intent(text):
    for intent, patterns in intent_patterns.items():
        if any(pattern in text for pattern in patterns):
            return intent
    return "unknown"

def extract_entities(text):
    doc = nlp(text)
    entities = [(ent.text, ent.label_) for ent in doc.ents]
    return entities

# Create training data from patterns
texts = []
labels = []

for intent, phrases in intent_patterns.items():
    for phrase in phrases:
        texts.append(phrase)
        labels.append(intent)

# Create DataFrame for training
training_data = pd.DataFrame({'cleaned_text': texts, 'intent': labels})

from sklearn.model_selection import train_test_split
# Split data into training and validation sets
X_train, X_test, y_train, y_test = train_test_split(training_data['cleaned_text'], training_data['intent'], test_size=0.2, random_state=42)

from sklearn.feature_extraction.text import TfidfVectorizer
# Convert text to features using TF-IDF
vectorizer = TfidfVectorizer(ngram_range=(1, 3))
X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

model = LogisticRegression(max_iter=3000)
model.fit(X_train_tfidf, y_train)

# Evaluate the model
y_pred = model.predict(X_test_tfidf)
print(classification_report(y_test, y_pred))

cleaned_tfidf = vectorizer.transform(conversation_data['cleaned_text'])
predicted_intents = model.predict(cleaned_tfidf)

conversation_data['intent'] = predicted_intents

conversation_data.head()

import matplotlib.pyplot as plt
import seaborn as sns


intent_counts = conversation_data['intent'].value_counts().reset_index()
intent_counts.columns = ['Intent', 'Count']
print("Intent Distribution Table:\n", intent_counts)

# Plot the intent distribution
plt.figure(figsize=(10, 6))
sns.countplot(x='intent', data=conversation_data, order=conversation_data['intent'].value_counts().index, palette='Set2')

# Beautify the plot
plt.title('Distribution of Intents in Dataset', fontsize=14)
plt.xlabel('Intent', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()

# Show the plot
plt.show()

from sklearn.preprocessing import LabelEncoder
# 3. Encode the Intent Labels
label_encoder = LabelEncoder()
conversation_data['intent_encoded'] = label_encoder.fit_transform(conversation_data['intent'])

# 4. Tokenize and Pad the Text Data
max_words = 5000  # Vocabulary size
max_len = 50    # Max length of padded sequences

pip install tensorflow

from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(num_words=max_words, oov_token="<OOV>")
tokenizer.fit_on_texts(conversation_data['cleaned_text'])

conversation_data.head()

from sklearn.model_selection import train_test_split

train_data, test_data = train_test_split(conversation_data, test_size=0.2, random_state=42)

print(f"Training samples: {len(train_data)}, Testing samples: {len(test_data)}")

#pip install wordcloud

from wordcloud import WordCloud
import matplotlib.pyplot as plt

# Ensure text corpus is correctly joined
text_corpus = ' '.join(conversation_data["cleaned_text"].dropna())

# Generate Word Cloud
wordcloud = WordCloud(width=800, height=400, background_color='white').generate(text_corpus)

# Display the Word Cloud
plt.figure(figsize=(10, 5))
plt.imshow(wordcloud, interpolation='bilinear')
plt.axis("off")
plt.title("Word Cloud of Cleaned Text")
plt.show()

# Visual 4: Text Length Distribution
conversation_data["text_length"] = conversation_data["cleaned_text"].apply(len)
plt.figure(figsize=(8, 5))
sns.histplot(conversation_data["text_length"], bins=30, kde=True, color="royalblue")
plt.title("Text Length Distribution")
plt.xlabel("Length of Cleaned Text")
plt.ylabel("Frequency")
plt.show()

from collections import Counter
from nltk import ngrams
import itertools

# Helper function to generate n-grams from cleaned text
def get_ngrams(text_list, n):
    ngram_list = list(itertools.chain(*[ngrams(text.split(), n) for text in text_list]))
    return [" ".join(ngram) for ngram in ngram_list]

# Extract cleaned text from the DataFrame
cleaned_texts = conversation_data["cleaned_text"].dropna()

# Get most common unigrams, bigrams, trigrams
unigrams = Counter(get_ngrams(cleaned_texts, 1)).most_common(10)   # Most common 1-word combinations
bigrams = Counter(get_ngrams(cleaned_texts, 2)).most_common(10)    # Most common 2-word combinations
trigrams = Counter(get_ngrams(cleaned_texts, 3)).most_common(10)   # Most common 3-word combinations

# Function to plot n-gram frequency (with hue fix for Seaborn v0.14+)
def plot_ngram_distribution(ngram_counts, title):
    ngrams, counts = zip(*ngram_counts)
    ngram_series = pd.Series(ngrams)

    plt.figure(figsize=(10, 5))
    sns.barplot(
        x=list(counts),
        y=ngram_series,
        hue=ngram_series,  # Set hue to the y-axis variable
        palette="Set2",
        legend=False  # Avoid duplicate legends
    )
    plt.title(title)
    plt.xlabel("Frequency")
    plt.ylabel("N-Grams")
    plt.show()

# Plot the distributions
plot_ngram_distribution(unigrams, "Top 10 Most Common Words (Unigrams)")
plot_ngram_distribution(bigrams, "Top 10 Most Common 2-Word Phrases (Bigrams)")
plot_ngram_distribution(trigrams, "Top 10 Most Common 3-Word Phrases (Trigrams)")

conversation_data["entities"] = conversation_data["text"].apply(lambda x: extract_entities(x) if pd.notna(x) else [])
import matplotlib.pyplot as plt

# Flatten entity labels
entity_types = [label for sublist in conversation_data["entities"] for _, label in sublist]

# Convert to a Pandas Series for easier ordering
entity_series = pd.Series(entity_types)

# Visual 3: Entity Types Distribution
plt.figure(figsize=(8, 5))
sns.countplot(
    y=entity_series,
    hue=entity_series,  # Assigning hue to match the y-axis
    order=entity_series.value_counts().index,
    palette="Set3",
    legend=False  # Remove the duplicate legend
)
plt.title("Entity Types Distribution")
plt.xlabel("Count")
plt.ylabel("Entity Type")
plt.show()

#pip install tf-keras

#  Metrics Calculation (Accuracy, F1, Precision, Recall)
def compute_metrics(pred):
    predictions = np.argmax(pred.predictions, axis=1)
    labels = pred.label_ids
    acc = accuracy_score(labels, predictions)
    f1 = f1_score(labels, predictions, average="weighted")
    precision = precision_score(labels, predictions, average="weighted", zero_division=0)
    recall = recall_score(labels, predictions, average="weighted", zero_division=0)
    return {"accuracy": acc, "f1": f1, "precision": precision, "recall": recall}

import torch
from torch.utils.data import Dataset, DataLoader
class IntentDataset(torch.utils.data.Dataset):
    def __init__(self, texts, speakers, labels, tokenizer):
        # Include speaker in the text
        self.encodings = tokenizer(
            [f"[{s}] {t}" for s, t in zip(speakers, texts)],
            padding="max_length",
            truncation=True,
            max_length=256
        )
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {**{k: torch.tensor(v[idx]) for k, v in self.encodings.items()}, "labels": torch.tensor(self.labels[idx])}

"""### Bert Tokenizer"""

import torch
from torch.utils.data import Dataset, DataLoader
from transformers import BertTokenizer, BertForSequenceClassification, Trainer, TrainingArguments

# Load BERT tokenizer and model
tokenizer = BertTokenizer.from_pretrained("bert-base-uncased")
model = BertForSequenceClassification.from_pretrained("bert-base-uncased", num_labels=len(conversation_data['intent_encoded'].unique()))

# Prepare datasets
train_dataset = IntentDataset(train_data['cleaned_text'].tolist(), train_data['speaker'].tolist(), train_data['intent_encoded'].tolist(), tokenizer)
test_dataset = IntentDataset(test_data['cleaned_text'].tolist(), train_data['speaker'].tolist(), test_data['intent_encoded'].tolist(), tokenizer)

# Training arguments
training_args = TrainingArguments(
    output_dir='./banking_intent_model',
    evaluation_strategy="epoch",
    save_strategy="epoch",
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    logging_dir='./logs',
    logging_steps=10,
    num_train_epochs=1,
    report_to="none"
)

# Initialize Trainer
bert_trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics,
)

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
import numpy as np
import pandas as pd
# Fine-tune BERT
bert_trainer.train()

# Save model and tokenizer
model.save_pretrained("/content/drive/MyDrive/chatbot/bert_intent_model")
tokenizer.save_pretrained("/content/drive/MyDrive/chatbot/bert_intent_model")

from sklearn.metrics import accuracy_score, classification_report

results = bert_trainer.evaluate(test_dataset)
print("Evaluation Metrics:", results)

"""### Fine-Tune DistilBERT"""

# Encode Intent Labels
label2id = {label: i for i, label in enumerate(conversation_data['intent'].unique())}
id2label = {i: label for label, i in label2id.items()}
conversation_data['intent_encoded_Distil_bert'] = conversation_data['intent'].map(label2id)

from transformers import DistilBertTokenizer, DistilBertForSequenceClassification, Trainer, TrainingArguments
tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")

# Prepare datasets
train_dataset = IntentDataset(train_data['cleaned_text'].tolist(), train_data['speaker'].tolist(), train_data['intent_encoded'].tolist(), tokenizer)
test_dataset = IntentDataset(test_data['cleaned_text'].tolist(), train_data['speaker'].tolist(), test_data['intent_encoded'].tolist(), tokenizer)

from transformers import DistilBertTokenizer, DistilBertForSequenceClassification, Trainer, TrainingArguments
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
import numpy as np
import pandas as pd
# ✅ Load Pretrained DistilBERT Model
model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=len(label2id),
    id2label=id2label,
    label2id=label2id
)

# ✅ Set Training Arguments
training_args = TrainingArguments(
    output_dir="./distilbert-intent-model",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    logging_dir="./logs",
    logging_steps=50,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=1,
    report_to="tensorboard",
)

distilbert_trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics,
)

# ✅ Train the Model (with Metrics Tracking)
distilbert_trainer.train()

# Save model and tokenizer
model.save_pretrained("/content/drive/MyDrive/chatbot/distilbert_intent_model")
tokenizer.save_pretrained("/content/drive/MyDrive/chatbot/distilbert_intent_model")

distil_results = distilbert_trainer.evaluate(test_dataset)
print("Evaluation Metrics:", distil_results)

"""### Chat-gpt-2"""

from transformers import GPT2ForSequenceClassification, GPT2Tokenizer, Trainer, TrainingArguments
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
import torch
import numpy as np

#  Load GPT-2 model and tokenizer for classification
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
model = GPT2ForSequenceClassification.from_pretrained("gpt2", num_labels=len(intent_patterns))

#  Set padding token (GPT-2 doesn't have one by default)
tokenizer.pad_token = tokenizer.eos_token  # Use EOS token as padding
model.config.pad_token_id = tokenizer.pad_token_id

# Prepare datasets
train_dataset = IntentDataset(train_data['cleaned_text'].tolist(), train_data['speaker'].tolist(), train_data['intent_encoded'].tolist(), tokenizer)
test_dataset = IntentDataset(test_data['cleaned_text'].tolist(), train_data['speaker'].tolist(), test_data['intent_encoded'].tolist(), tokenizer)

#  Prepare datasets
# train_dataset = IntentDataset(train_data['cleaned_text'].tolist(), train_data['intent_encoded'].tolist())
# test_dataset = IntentDataset(test_data['cleaned_text'].tolist(), test_data['intent_encoded'].tolist())

#  Set training arguments
training_args = TrainingArguments(
    output_dir="./gpt2_intent_results",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=5e-5,
    per_device_train_batch_size=8,  # Ensure batch size > 1 works
    per_device_eval_batch_size=8,
    num_train_epochs=1,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=200,
)

#  Initialize Trainer
chatgpt_trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics,
)

chatgpt_trainer.train()

# ✅ Save the model and tokenizer
model.save_pretrained("/content/drive/MyDrive/chatbot/gpt2_intent_classifier")
tokenizer.save_pretrained("/content/drive/MyDrive/chatbot/gpt2_intent_classifier")

# ✅ Evaluate the model
chatgpt_results = chatgpt_trainer.evaluate(test_dataset)
print("Test Results: ", chatgpt_results)

"""RoBerta Model"""

from transformers import RobertaForSequenceClassification, RobertaTokenizer, Trainer, TrainingArguments
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
import torch

# ✅ Load RoBERTa model and tokenizer for classification
tokenizer = RobertaTokenizer.from_pretrained("roberta-base")
model = RobertaForSequenceClassification.from_pretrained("roberta-base", num_labels=len(intent_patterns))

# ✅ Custom Dataset Class (with Tokenizer)
class IntentDataset(torch.utils.data.Dataset):
    def __init__(self, texts, labels, tokenizer):
        self.encodings = tokenizer(texts, padding="max_length", truncation=True, max_length=256)
        self.labels = labels

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {**{k: torch.tensor(v[idx]) for k, v in self.encodings.items()}, "labels": torch.tensor(self.labels[idx])}

# Prepare datasets
train_dataset = IntentDataset(train_data['cleaned_text'].tolist(), train_data['speaker'].tolist(), train_data['intent_encoded'].tolist(), tokenizer)
test_dataset = IntentDataset(test_data['cleaned_text'].tolist(), train_data['speaker'].tolist(), test_data['intent_encoded'].tolist(), tokenizer)

# ✅ Set training arguments
training_args = TrainingArguments(
    output_dir="./llama_intent_results",     # Directory to save checkpoints
    evaluation_strategy="epoch",             # Evaluate after each epoch
    save_strategy="epoch",                   # Save model checkpoints every epoch
    learning_rate=2e-5,                      # Lower learning rate for large models
    per_device_train_batch_size=4,           # Reduce batch size for LLaMA (GPU intensive)
    per_device_eval_batch_size=4,
    num_train_epochs=1,                      # Number of epochs
    weight_decay=0.01,                       # Regularization
    logging_dir="./logs",                    # Log directory
    logging_steps=100,                       # Log every 100 steps
    load_best_model_at_end=True,             # Save the best model
    fp16=True,                               # Mixed precision (faster on modern GPUs)
    push_to_hub=False,                       # Disable auto-push to Hugging Face Hub
)

# ✅ Initialize Trainer
RoBerta_trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics,
)

from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score
import numpy as np
import pandas as pd
# ✅ Train the model
RoBerta_trainer.train()

# ✅ Save the model and tokenizer
model.save_pretrained("/content/drive/MyDrive/chatbot/roberta_classifier")
tokenizer.save_pretrained("/content/drive/MyDrive/chatbot/roberta_classifier")

# ✅ Evaluate the model
Roberta_results = RoBerta_trainer.evaluate()
print("Test Results: ", Roberta_results)

eval_results = {
    "BERT": {
        "eval_loss": 0.063544,
        "eval_accuracy": 0.9837,
        "eval_f1": 0.983489,
        "eval_precision": 0.983425,
        "eval_recall": 0.9837,
        "eval_latency": 0.010713,
        "eval_cpu_percent": 0.0,
        "eval_memory_used_mb": 2521.886719,
        "eval_runtime": 71.7853,
        "eval_samples_per_second": 139.304,
        "eval_steps_per_second": 8.707,
        "epoch": 1.0
    },
    "DistilBERT": {
        "eval_loss": 0.070151,
        "eval_accuracy": 0.9793,
        "eval_f1": 0.979069,
        "eval_precision": 0.979103,
        "eval_recall": 0.9793,
        "eval_latency": 0.021102,
        "eval_cpu_percent": 0.0,
        "eval_memory_used_mb": 2515.113281,
        "eval_runtime": 71.6437,
        "eval_samples_per_second": 139.580,
        "eval_steps_per_second": 8.724,
        "epoch": 1.0
    },
    "ChatGPT-2": {
        "eval_loss": 0.114259,
        "eval_accuracy": 0.9733,
        "eval_f1": 0.972986,
        "eval_precision": 0.973100,
        "eval_recall": 0.9733,
        "eval_latency": 0.010446,
        "eval_cpu_percent": 0.0,
        "eval_memory_used_mb": 3109.269531,
        "eval_runtime": 163.6402,
        "eval_samples_per_second": 61.110,
        "eval_steps_per_second": 7.639,
        "epoch": 1.0
    },
    "RoBERTa": {
        "eval_loss": 0.245989,
        "eval_accuracy": 0.9559,
        "eval_f1": 0.955277,
        "eval_precision": 0.955431,
        "eval_recall": 0.9559,
        "eval_latency": 0.013138,
        "eval_cpu_percent": 0.0,
        "eval_memory_used_mb": 3352.175781,
        "eval_runtime": 44.1185,
        "eval_samples_per_second": 226.663,
        "eval_steps_per_second": 56.666,
        "epoch": 1.0
    }
}

import pandas as pd
# Create a DataFrame
df = pd.DataFrame.from_dict(eval_results, orient='index')

df

import matplotlib.pyplot as plt
import seaborn as sns

# Metrics to plot
metrics = ['accuracy', 'precision', 'recall', 'f1']

# Prepare data
plot_df = df.reset_index().rename(columns={'index': 'Model'})
plot_df = plot_df[['Model', 'eval_accuracy', 'eval_precision', 'eval_recall', 'eval_f1']]
plot_df = plot_df.rename(columns={
    'eval_accuracy': 'accuracy',
    'eval_precision': 'precision',
    'eval_recall': 'recall',
    'eval_f1': 'f1'
})

# Plot
fig, axes = plt.subplots(2, 2, figsize=(12, 8))
axes = axes.flatten()

for i, metric in enumerate(metrics):
    ax = axes[i]
    sns.barplot(data=plot_df, x='Model', y=metric, hue='Model', dodge=False, palette='rocket', ax=ax, legend=False)
    ax.set_title(f'{metric.capitalize()} Comparison')
    ax.tick_params(axis='x', rotation=45)
    ax.set_ylim([0.8, 1.0])

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Create a new DataFrame for plotting latency + accuracy
plot_df = df.reset_index().rename(columns={'index': 'Model'})
plot_df['accuracy_percent'] = plot_df['eval_accuracy'] * 100  # convert to percent

# Plotting
plt.figure(figsize=(8, 6))
ax = sns.barplot(data=plot_df, x='Model', y='eval_latency', hue='Model', dodge=False, palette='bright', legend=False)

# Annotate each bar with accuracy
for bar, acc in zip(ax.patches, plot_df['accuracy_percent']):
    height = bar.get_height()
    ax.annotate(f'{acc:.2f}%',
                xy=(bar.get_x() + bar.get_width() / 2, height),
                xytext=(0, 5),
                textcoords='offset points',
                ha='center', va='bottom',
                fontsize=10, color='black')

# Customize plot
ax.set_title('Model Latency with Accuracy Annotation')
ax.set_ylabel('Latency (seconds)')
ax.set_xlabel('Model')
ax.tick_params(axis='x', rotation=45)
plt.tight_layout()
plt.show()

"""**LLaMA (Large Language Model Meta AI)**"""

!pip install torch transformers accelerate bitsandbytes

from transformers import LlamaForCausalLM, LlamaTokenizer
import torch

model_name = "meta-llama/Llama-2-7b-chat-hf"

tokenizer = LlamaTokenizer.from_pretrained(model_name, use_auth_token="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")
model = LlamaForCausalLM.from_pretrained(model_name, use_auth_token="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", torch_dtype=torch.float16, device_map="auto")

# Function to predict intent
def predict_intent(text):
    prompt = f"""
You are an AI assistant helping to classify user messages into intents.

Here are some possible intents:
- greeting
- update_personal_info
- verify_identity
- get_account_number
- set_up_payments

Message: "{text}"
Intent:"""

    inputs = tokenizer(prompt, return_tensors="pt").to("cuda")
    outputs = model.generate(**inputs, max_new_tokens=20)
    response = tokenizer.decode(outputs[0], skip_special_tokens=True)

    # Extract just the intent from response
    predicted = response.split("Intent:")[-1].strip().split("\n")[0]
    return predicted

conversation_data['llama_predicted_intent'] = conversation_data['cleaned_text'].head(10000).apply(predict_intent)

# Save to new file
conversation_data.to_csv("banking_with_llama_predictions.csv", index=False)

from sklearn.metrics import accuracy_score, classification_report

# Ensure both columns are strings
conversation_data['intent_encoded'] = conversation_data['intent_encoded'].astype(str)
conversation_data['llama_predicted_intent'] = conversation_data['llama_predicted_intent'].astype(str)

# Accuracy
acc = accuracy_score(conversation_data['intent_encoded'], conversation_data['llama_predicted_intent'])
print(f"Accuracy: {acc:.2%}")

# Full classification report
print("\n📋 Classification Report:")
print(classification_report(conversation_data['intent_encoded'], conversation_data['llama_predicted_intent']))

class IntentDataset(Dataset):
    def __init__(self, texts, speakers, intents, tokenizer, max_length=256):
        self.encodings = tokenizer(texts, padding="max_length", truncation=True, max_length=max_length)
        self.speakers = speakers
        self.labels = intents

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        return {
            "input_ids": torch.tensor(self.encodings["input_ids"][idx]),
            "attention_mask": torch.tensor(self.encodings["attention_mask"][idx]),
            "labels": torch.tensor(self.labels[idx]),
        }

tokenizer.pad_token = tokenizer.eos_token  # Use EOS token as padding
model.config.pad_token_id = tokenizer.pad_token_id

# Tokenization
train_dataset = IntentDataset(
    train_data["cleaned_text"].tolist(),
    train_data["speaker"].tolist(),
    train_data["intent_encoded"].tolist(),
    tokenizer
)

test_dataset = IntentDataset(
    test_data["cleaned_text"].tolist(),
    test_data["speaker"].tolist(),
    test_data["intent_encoded"].tolist(),
    tokenizer
)

!pip uninstall keras -y
!pip install keras==2.15

from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="./llama2_intent_results",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=5e-5,
    per_device_train_batch_size=4,  # Reduce if memory issues
    per_device_eval_batch_size=4,
    num_train_epochs=1,
    weight_decay=0.01,
    logging_dir="./logs",
    logging_steps=200,
    push_to_hub=False
)

llama_trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics,
)

llama_trainer.train()